### ISSUE TITLE
handle n conflicts

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_git_conflict#2]
file
```
$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later

$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later

$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later
```

if I place caret between 1st and 2nd, it takes 1st anyway.
if I place caret between 2nd and 3rd it takes 1st anyway

**Comment by Alexey-T** [comment]
maybe it's ok but not handy if I have n small conflicts on big screen.

**Comment by halfbrained** [comment]
No, you are definitely right. Am fixing it

**Comment by halfbrained** [comment]
Fixed.

Now if caret is on screen I search below caret on screen, then above caret on screen, if no conflicts on screen - search offscreen down. (more efficiently than described here, but the result is the same)

If caret is not on screen - just search from first visible line.

I think this is the closest to expected behavior.
